version: '3'

tasks:
  deploy_fr:
    desc: uiのビルドをしてデプロイする
    cmds:
      - git fetch
      - git pull
      - reflex export --frontend-only
      - sudo rm -rf frontend/*
      - sudo unzip frontend.zip -d frontend
  deploy_bg:
    desc: backendのデプロイする
    cmds:
      - git fetch
      - git pull
      - sudo systemctl restart holomoti.service